import { Inter, Open_Sans, Roboto_Slab } from "next/font/google";

import type { Metadata } from "next";

import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});
const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-small-subtitle",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`
      ${openSans.className} ${openSans.variable}
      ${inter.className} ${inter.variable}
      ${robotoSlab.className} ${robotoSlab.variable}
    `}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
