import { Inter, Open_Sans, Roboto_Slab } from "next/font/google";

import type { Metadata } from "next";

import "./globals.css";

import Footer from "@/components/Footer";
import HeaderBar from "@/components/HeaderBar";
import HeaderBarSpace from "@/components/HeaderBarSpace";
import "react-material-symbols/rounded";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const openSans = Open_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-body",
// });
// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-heading",
// });
// const robotoSlab = Roboto_Slab({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-small-subtitle",
// });

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-small-subtitle",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${openSans.variable} ${inter.variable} ${robotoSlab.variable}`}>
      <body>
        <HeaderBar />
        <HeaderBarSpace />
        {children}
        <Footer />
      </body>
    </html>
  );
}
